version: "2.1"

volumes:
  interface_db:
  wifi_db:
  syncthing:
  fdroid:
  mapeo:
  crawls:
  pywb-archive:
  installers:
  postgres_data:
  mbtiles:
  terrastories-bundler:
  terrastories-media:
  terrastories-import:
  pataka:
services:
  # https://github.com/digidem/starter-interface
  balena-interface:
    build: services/interface
    restart: always
    environment:
      NETWORK_MODE: bridge
    ports:
      - "8090:80"
      - "8079:8079"
    volumes:
      - interface_db:/app/db # Stores UI database files
      - crawls:/app/storage/websites
      - mapeo:/app/storage/mapeo
      - fdroid:/app/storage/fdroid
      - installers:/app/storage/installers
      - mbtiles:/app/storage//mbtiles
      - terrastories-import:/app/storage/terrastories/import
      - terrastories-media:/app/storage/terrastories/media
    privileged: true # This can be removed if not using the USB mounting feature
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1
  # https://github.com/balena-labs-research/python-wifi-connect
  # https://github.com/balena-os/wifi-connect
  wifi:
    restart: always
    build: services/wifi-connect
    network_mode: "host"
    labels:
        io.balena.features.dbus: '1'
    cap_add:
        - NET_ADMIN
    environment:
        DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
  # https://hub.docker.com/r/communityfirst/edt-offline-edt-portal
  portal:
    image: communityfirst/edt-offline-portal:training
    restart: always
    ports:
      - 8080:3000
  # https://hub.docker.com/r/communityfirst/mapeo-bridge
  mapeo-bridge:
    image: communityfirst/mapeo-bridge
    network_mode: host
    volumes:
      - terrastories-import:/usr/src/output
    environment:
      CSV_PATH: /usr/src/output
    restart: unless-stopped
  # https://hub.docker.com/r/filebrowser/filebrowser
  filebrowser:
    build: services/filebrowser
    restart: unless-stopped
    volumes:
      - crawls:/srv/websites
      - mapeo:/srv/mapeo
      - fdroid:/srv/fdroid
      - installers:/srv/installers
      - mbtiles:/srv/mbtiles
      - terrastories-import:/srv/terrastories/import
      - terrastories-media:/srv/terrastories/media
    ports:
      - 8081:80
    command: -- c
  # https://hub.docker.com/r/linuxserver/syncthing/
  syncthing:
    build: services/syncthing
    volumes:
      - syncthing:/config
      - crawls:/data/websites
      - mapeo:/data/mapeo
      - fdroid:/data/fdroid
      - installers:/data/installers
      - mbtiles:/data/mbtiles
    ports:
      - 8082:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  # https://hub.docker.com/_/postgres
  terrastories-db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: terrastories
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped
  # https://hub.docker.com/r/terrastories/terrastories
  terrastories:
    build: services/terrastories
    ports:
      - 8083:3000
    depends_on:
      - terrastories-db
    environment:
      DATABASE_URL: postgres://postgres:postgres@terrastories-db:5432/terrastories
      CHOKIDAR_USEPOLLING: 'true'
      SECRET_KEY_BASE: "a845b372237fe58988e8fb7698b9a7b61f8cc7581dc685387ff1cb8ec5f250d57b733379d53f5c3e7b816d0bf0fdf5f7b02558c64b932903e5ec3fbe10c4b205"
    volumes:
      - terrastories-bundler:/usr/local/bundle
      - terrastories-media:/media
      - terrastories-import:/api/import/media
    restart: unless-stopped
  # https://hub.docker.com/r/maptiler/tileserver-gl
  tileserver:
    build: services/tileserver
    ports:
      - 8085:8080
    volumes:
      - mbtiles:/data
    restart: unless-stopped
  # https://hub.docker.com/r/webrecorder/pywb
  pywb:
    build: services/pywb
    ports:
      - 8086:8080
    volumes:
      - pywb-archive:/webarchive
      - crawls:/source
    restart: unless-stopped
  # https://hub.docker.com/_/httpd
  httpd:
    build: services/httpd
    ports:
      - 8087:80
    volumes:
      - installers:/usr/local/apache2/htdocs/installers
      - fdroid:/usr/local/apache2/htdocs/repo
      - mapeo:/usr/local/apache2/htdocs/mapeo
      - mbtiles:/usr/local/apache2/htdocs/mbtiles
    restart: unless-stopped
  # https://hub.docker.com/r/communityfirst/pataka-cli
  pataka:
    image: communityfirst/pataka-cli:latest
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - pataka:/root/.local/share/ahau-pataka
    environment:
      PATAKA_WEB_PORT: 8089
