version: '3'
services:
  # https://containrrr.dev/watchtower
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60
  # https://hub.docker.com/r/communityfirst/mapeo-icons
  mapeo-icons:
    image: communityfirst/mapeo-icons
    restart: always
    environment:
      VIRTUAL_HOST: ${DOMAIN_ICONS}
      LETSENCRYPT_HOST: ${DOMAIN_ICONS}
      LETSENCRYPT_EMAIL: ${EMAIL}
      ICONS_TO_DOWNLOAD: ${ICONS_TO_DOWNLOAD}
      NOUN_KEY: ${NOUN_KEY}
      NOUN_SECRET: ${NOUN_SECRET}
      VIRTUAL_PORT: 3000
  # https://hub.docker.com/r/nginxproxy/nginx-proxy
  proxy:
    build: ../../services/nginx-proxy
    restart: always
    container_name: proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DIR}/app-data/proxy/certs:/etc/nginx/certs:ro
      - ${DIR}/app-data/proxy/vhostd:/etc/nginx/vhost.d
      - ${DIR}/app-data/proxy/html:/usr/share/nginx/html
      - ${DIR}/app-data/proxy/nginx-conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
  # https://hub.docker.com/r/nginxproxy/acme-companion
  ssl:
    image: nginxproxy/acme-companion:latest
    restart: always
    container_name: ssl
    environment:
      NGINX_PROXY_CONTAINER: proxy
      DEFAULT_EMAIL: ${EMAIL}
    volumes:
      - ${DIR}/app-data/proxy/certs:/etc/nginx/certs
      - ${DIR}/app-data/proxy/vhostd:/etc/nginx/vhost.d
      - ${DIR}/app-data/proxy/html:/usr/share/nginx/html
      - ${DIR}/app-data/proxy/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
  # https://hub.docker.com/_/httpd
  fdroid-repo:
    image: httpd:latest
    restart: always
    volumes:
      -  ${DIR}/content/fdroid-repository:/usr/local/apache2/htdocs/
    environment:
      VIRTUAL_HOST: ${DOMAIN_FDROID}
      LETSENCRYPT_HOST: ${DOMAIN_FDROID}
      LETSENCRYPT_EMAIL: ${EMAIL}
  # https://filebrowser.org
  filebrowser:
    image: filebrowser/filebrowser:s6
    restart: always
    volumes:
      - ${DIR}:/srv
      - ${DIR}/app-data/filebrowser/database:/database
      - ${DIR}/app-data/filebrowser/config:/config
    environment:
      VIRTUAL_HOST: ${DOMAIN_FILEBROWSER}
      LETSENCRYPT_HOST: ${DOMAIN_FILEBROWSER}
      LETSENCRYPT_EMAIL: ${EMAIL}
      PGID: ${PGID}
      PUID: ${PUID}
  # https://hub.docker.com/r/minio/minio/
  minio:
    image: minio/minio
    restart: always
    dns:
      - 8.8.8.8
    ports:
      - 9000:9000
    volumes:
      - ${DIR}/content/:/data
    environment:
      VIRTUAL_HOST: ${DOMAIN_MINIO}
      LETSENCRYPT_HOST: ${DOMAIN_MINIO}
      LETSENCRYPT_EMAIL: ${EMAIL}
      VIRTUAL_PORT: 9001
      MINIO_ROOT_USER: ${ADMIN_MINIO}
      MINIO_ROOT_PASSWORD: ${PASSWORD_MINIO}
      # MINIO_BROWSER_REDIRECT_URL: https://[CI_CD_DOMAIN]
      # MINIO_SERVER_URL: https://[CI_CD_DOMAIN]:34256 
    command: server --address ":9000" --console-address ":9001" /data
  # https://hub.docker.com/r/linuxserver/syncthing/
  syncthing:
    image: lscr.io/linuxserver/syncthing
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      VIRTUAL_HOST: ${DOMAIN_SYNCTHING}
      LETSENCRYPT_HOST: ${DOMAIN_SYNCTHING}
      LETSENCRYPT_EMAIL: ${EMAIL}
      VIRTUAL_PORT: 8384
      TZ: America/Brasil
    volumes:
      - ${DIR}/app-data/syncthing:/config
      - ${DIR}/content:/data
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
  crawler:
    build: ../../services/crawler
    restart: always
    volumes:
        - ${DIR}/app-data/crawls:/crawls/
        - ${DIR}/content:/app/content
    environment:
      VIRTUAL_HOST: ${DOMAIN_CRAWLER}
      LETSENCRYPT_HOST: ${DOMAIN_CRAWLER}
      LETSENCRYPT_EMAIL: ${EMAIL}
      VIRTUAL_PORT: 8080
      CRAWL_TIMER: ${CRAWL_TIMER}
  # TODO: Terrastories
  # V2: Open Balena