version: '2.1'

volumes:
  fdroid:
  portal:
  mapeo:
  crawls:
  pywb-archive:
  minio-data:
  installers:
  # Terrastories
  postgres_data:
  mbtiles:
  bundler:
  terrastories-data:
  terrastories-media:
  terrastories-import:
services:
  # https://github.com/balena-os/wifi-connect
  wifi:
    restart: always
    build: ../../services/wifi-connect
    volumes:
      - /var/run/dbus:/var/run/dbus
    network_mode: "host"
    privileged: true
    environment:
      PORTAL_SSID: ${PORTAL_SSID}
  # https://hub.docker.com/_/httpd
  portal:
    image: communityfirst/edt-offline-portal:nightly-full
    restart: always
    volumes:
      - 'portal:/usr/src/nuxt-app'
    ports:
      - 8080:3000
  # https://hub.docker.com/repository/docker/communityfirst/mapeo-bridge
  mapeo-bridge:
    image: communityfirst/mapeo-bridge
    network_mode: host
    volumes:
      - terrastories-import:/usr/src/output
    restart: unless-stopped
    environment:
      MAPEO_PROJECT_KEY: ${MAPEO_PROJECT_KEY}
      MAPEO_STORAGE_PATH: ${MAPEO_STORAGE_PATH}
      MAPEO_TERRASTORIES_TYPE: ${MAPEO_TERRASTORIES_TYPE}
      CSV_PATH: /usr/src/output
  # https://hub.docker.com/r/minio/minio/
  minio:
    image: minio/minio
    restart: always
    dns:
      - 8.8.8.8
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio-data:/data'
    environment:
      MINIO_ROOT_USER: ${ADMIN_LOGIN}
      MINIO_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    command: server --address ":9000" --console-address ":9001" /data
  # https://hub.docker.com/r/filebrowser/filebrowser
  filebrowser:
    build: ../../services/filebrowser
    restart: unless-stopped
    volumes:
      - crawls:/srv/websites
      - mapeo:/srv/mapeo
      - fdroid:/srv/fdroid
      - installers:/srv/installers
      - terrastories-import:/srv/terrastories/import
      - terrastories-media:/srv/terrastories/media
    environment:
      PUID: 1000
      PGID: 1000
      ADMIN_LOGIN: ${ADMIN_LOGIN}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LOCALE: ${LOCALE}
    ports:
      - 8081:80
    command: -- c
  # https://hub.docker.com/r/linuxserver/syncthing/
  syncthing:
    build: ../../services/syncthing
    environment:
      PUID: 1000
      PGID: 1000
      ADMIN_LOGIN: ${ADMIN_LOGIN}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      TZ: America/Brasil
      SYNC_SOURCE_ID: ${SYNC_SOURCE_ID}
      SYNC_SOURCE_NAME: ${SYNC_SOURCE_NAME}
      SYNC_CRAWLS_ID: ${SYNC_CRAWLS_ID}
      SYNC_CRAWLS_NAME: ${SYNC_CRAWLS_NAME}
      SYNC_FDROID_ID: ${SYNC_FDROID_ID}
      SYNC_FDROID_NAME: ${SYNC_FDROID_NAME}
      SYNC_MAPEO_ID: ${SYNC_MAPEO_ID}
      SYNC_MAPEO_NAME: ${SYNC_MAPEO_NAME}
      SYNC_INSTALLERS_ID: ${SYNC_INSTALLERS_ID}
      SYNC_INSTALLERS_NAME: ${SYNC_INSTALLERS_NAME}
      SYNC_TILES_ID: ${SYNC_TILES_ID}
      SYNC_TILES_NAME: ${SYNC_TILES_NAME}
    volumes:
      - crawls:/config/websites
      - mapeo:/config/mapeo
      - fdroid:/config/fdroid
      - installers:/config/installers
    ports:
      - 8082:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  # https://hub.docker.com/r/communityfirst/pywb
  pywb:
    build: ../../services/pywb
    ports:
      - 8086:8080
    volumes:
      - pywb-archive:/webarchive
      - crawls:/source
  # https://hub.docker.com/r/maptiler/tileserver-gl
  tileserver:
    build: ../../services/tileserver
    ports:
      - 8085:8080
    volumes:
      - mbtiles:/data
  # https://hub.docker.com/_/httpd
  httpd:
    build: ../../services/httpd
    ports:
      - 8087:80
    volumes:
      - installers:/usr/local/apache2/htdocs/installers
      - fdroid:/usr/local/apache2/htdocs/repo
  # Terrastories
  terrastories-db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: terrastories
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  terrastories:
    build: ../../services/terrastories
    ports:
      - 8083:3000
    depends_on:
      - terrastories-db
    environment:
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
      DATABASE_URL: postgres://postgres:postgres@terrastories-db:5432/terrastories
      RAILS_ENV: ${RAILS_ENV}
      CHOKIDAR_USEPOLLING: 'true'
      USE_LOCAL_MAP_SERVER: ${USE_LOCAL_MAP_SERVER}
      OFFLINE_MAP_STYLE: ${OFFLINE_MAP_URL}
      SECRET_KEY_BASE: "a845b372237fe58988e8fb7698b9a7b61f8cc7581dc685387ff1cb8ec5f250d57b733379d53f5c3e7b816d0bf0fdf5f7b02558c64b932903e5ec3fbe10c4b205"
      HOST_HOSTNAME: ${HOST_HOSTNAME}
    volumes:
      - bundler:/usr/local/bundle
      - terrastories-data:/api
      - terrastories-media:/media
      - terrastories-import:/api/import/media

