FROM ghcr.io/balena-labs-research/bsi:0.0.17

COPY config.yml .

# Optionally copy in your own header logo to replace the default.
COPY ../filebrowser/custom/branding/img/logo.svg public/ # Your logo for displaying on white backgrounds
COPY ../filebrowser/custom/branding/img/logo.svg public/ # Your logo for displaying on coloured background

