FROM communityfirst/balena-interface:latest

COPY config.yml .

# Optionally copy in your own header logo to replace the default.
COPY ./custom/logo_colour.svg public/logo_colour.svg
COPY ./custom/logo_white.svg public/logo_white.svg

