# pywb config file
# ========================================
#
debug: true
autoindex: 30
# TODO: Uncomment to set banner colors and logo
# ui:
  # logo: path/relative/from/static/logo.png
  # navbar_background_hex: 0c49b0
  # navbar_color_hex: fff
  # navbar_light_buttons: true

collections:
    all: $all
    earthdefenderstoolkit:
        index_paths: /webarchive
        archive_paths: /source

# Settings for each collection
use_js_obj_proxy: true

# Eanable Memento support
enable_memento: true

# Replay content in an iframe
framed_replay: false

redirect_to_exact: true

# Uncomment and change to set default locale
# TODO: set it to Docker env var
default_locale: en

# Uncomment to set available locales
locales:
   - en
   - es
   - pt