name: "Create Balena Image"
description: "Pre-loads, configures, compresses and uploads a Balena device"
inputs:
  balena_token:
    required: true
    description: "Balena token"
  balena_fleet:
    required: true
    description: "Target Balena fleet"
  github_ref:
    required: true
    description: "Github ref"
  github_head_ref:
    required: true
    description: "Github head ref"
  release_tag:
    description: "A tag to be used instead of the Github tag"
  balena_draft:
    required: false
    description: "Is this a release a draft"
  balena_path:
    description: "Path to read balena.yml file from"
    default: "./balena.yml"
outputs:
  github_tag:
    description: "Current Github tag"
    value: ${{ steps.get-ref.outputs.tag }}
  balena_tag:
    description: "Current Balena tag from balena.yml"
    value: ${{ steps.yaml-data.outputs.data }}
runs:
  using: "composite"
  steps:
    - name: Run read-yaml action
      id: yaml-data
      uses: jbutcher5/read-yaml@main # You may wish to replace main with a version tag such as '1.6' etc.
      with:
        file: ${{ inputs.balena_path }} # File to read from
        key-path: '["version"]' # Access the runs key then the using key and retuns the value.

    - name: Get the Ref
      id: get-ref
      uses: ankitvgupta/ref-to-tag-action@master
      with:
        ref: ${{ github.ref }}
        head_ref: ${{ github.head_ref }}

    - name: Balena Deploy
      uses: Theia-Scientific/balena-cli@v1
      if: success()
      with:
        balena_api_token: ${{inputs.balena_token}}
        balena_command: push ${{inputs.balena_fleet}} ${{inputs.balena_draft == 'true' && '--draft' || ''}} --release-tag v${{steps.yaml-data.outputs.data}}${{inputs.balena_draft && '-draft' || ''}} ${{ inputs.release_tag || steps.get-ref.outputs.tag }} ${{ inputs.commit && ('--release-tag commit $inputs.commit') || '' }}
