name: "Create release on Github"
description: "Downloads all artefacts, generates and publishes a release to Github"
inputs:
  pre-release:
    required: false
    description: "Is this a pre-release: true or false"
  repo_token:
    required: true
    description: "Github repository personal access token"
runs:
  using: "composite"
  steps:
    - name: Download all workflow artifacts
      uses: actions/download-artifact@v3
    - name: "✏️ Upload imgs and release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ inputs.repo_token }}"
        prerelease: ${{ inputs.pre-release }}
        files: |
          artifacts/*