seeds:
  - url: https://earthdefenderstoolkit.com
    include: earthdefenderstoolkit.com/(?:\?lang=)?es
    depth: 2
  - url: https://docs.mapeo.app/
    depth: 1
  - url: https://docs.terrastories.app/
    depth: 1
  - url: https://docs.earthdefenderstoolkit.com/
    depth: 1
combineWARCs: true
blockRules:
   - url: googleanalytics.com
netIdleWait: networkidle0
