seeds:
  - url: https://www.earthdefenderstoolkit.com
  - url: https://docs.mapeo.app/
  - url: https://docs.terrastories.app/
  - url: https://docs.earthdefenderstoolkit.com/
combineWARCs: true
blockRules:
   - url: googleanalytics.com
netIdleWait: networkidle0
