name: Balena Push Draft
on:
  push:
    branches-ignore:
      - main
jobs:
  balena-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Balena Deploy
        uses: Theia-Scientific/balena-cli@v1
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_TOKEN}}
          # TODO: tag draft release
          balena_command: "push ${{secrets.BALENA_FLEET}} --logs --draft"
