name: Balena Push Draft
on:
  push:
    branches-ignore:
      - main
jobs:
  balena-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './balena.yml'          # File to read from
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.
      - name: Balena Deploy
        uses: Theia-Scientific/balena-cli@v1
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_TOKEN}}
          balena_command: "push ${{secrets.BALENA_FLEET}} --draft --release-tag v${{steps.yaml-data.outputs.data}}-beta ${{github.ref_name}}"
