name: Balena Beta
on:
  push:
    branches:
      - main
jobs:
  balena-deploy:
    strategy:
      matrix:
        board: ['amd64', 'aarch64']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: "./balena.yml" # File to read from
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.
      - name: Balena Deploy
        uses: Theia-Scientific/balena-cli@v1
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_TOKEN}}
          balena_command: "push ${{secrets.BALENA_FLEET}}_${{matrix.board}} --draft --release-tag v${{steps.yaml-data.outputs.data}}-rc ${{ github.sha }}"
  balena-build-images:
    strategy:
      matrix:
        board: ['pi4', 'nuc']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get base board
        run: |
          if [ "${{ matrix.board }}" == 'pi4' ]; then
            echo "BALENA_IMAGE=raspberrypi4-64" >> $GITHUB_ENV
            echo "BALENA_ARCH=aarch64" >> $GITHUB_ENV
          elif [ "${{ matrix.board }}" == 'nuc' ]; then
            echo "BALENA_IMAGE=intel-nuc" >> $GITHUB_ENV
            echo "BALENA_ARCH=amd64" >> $GITHUB_ENV
          fi
      - name: balena CLI Action - download
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: |
            os download "$BALENA_IMAGE" \
              --output "$BALENA_IMAGE.img" \
              --version default
          balena_cli_version: 13.7.1

      - name: balena CLI Action - preload
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: |
            preload \
              "$BALENA_IMAGE.img" \
              --fleet "${{secrets.BALENA_FLEET}}_${{env.BALENA_ARCH}}" \
              --dont-check-arch  \
              --commit latest
          balena_cli_version: 13.7.1

      - name: balena CLI Action - configure
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: |
            os configure \
              "$BALENA_IMAGE.img" \
              --config-network=ethernet  \
              --fleet "${{secrets.BALENA_FLEET}}_${{env.BALENA_ARCH}}"
          balena_cli_version: 13.7.1

      - name: Zip image
        run: |
          zip -9 \
            "$(date -I)-$BALENA_IMAGE.zip" \
            "$BALENA_IMAGE.img"
      - uses: actions/upload-artifact@v3
        with:
          name: Release file
          path: "*.zip"