name: Balena Draft
on:
  pull_request:
    branches:
      - main

jobs:
  balena-deploy:
    strategy:
      matrix:
        board: ['amd64', 'aarch64']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './balena.yml'          # File to read from
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.
      - name: Set base board
        run: |
          if [ "${{ matrix.board }}" == 'amd64' ]; then
            echo "BALENA_ARCH=amd64" >> $GITHUB_ENV
          elif [ "${{ matrix.board }}" == 'aarch64' ]; then
            echo "BALENA_ARCH=aarch64" >> $GITHUB_ENV
          fi
      - name: Balena Deploy
        uses: Theia-Scientific/balena-cli@v1
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_TOKEN}}
          balena_command: "push ${{secrets.BALENA_FLEET}}_${{env.BALENA_ARCH}} --draft --release-tag commit ${{ github.sha }}  --release-tag v${{steps.yaml-data.outputs.data}}-draft ${{github.ref_name}}"
