name: Balena Draft
on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - 'balena.yml'
      - 'services/**'
    branches:
      - main

jobs:
  balena-deploy:
    strategy:
      matrix:
        fleet_var: ['_aarch64', '_amd64']
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.push-balena.outputs.hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Balena image
        uses: ./.github/actions/deploy-balena-image
        id: push-balena
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          balena_fleet: "${{ secrets.BALENA_FLEET }}${{ matrix.fleet_var }}"
          github_ref: ${{ github.ref }}
          github_head_ref: ${{ github.head_ref }}
          balena_release_type: draft
          release_tag: ${{ github.ref_name }}
          commit: $(git rev-parse HEAD)
