name: Cloud docker-compose Stack
on:
  pull_request:
    paths:
      - 'docker/cloud/**'
    branches:
      - main
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate .env file
        run: cp docker/cloud/.env.example docker/cloud/.env
      - name: Build the stack
        run: docker-compose -f docker/cloud/docker-compose.yml up -d
      # - name: Test # TODO add tests: filebrowser, syncthing, mapeo-icons, fdroid-repo
