name: Local docker-compose Stack
on:
  pull_request:
    paths:
      - 'compose/**'
    branches:
      - main
jobs:
  test-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate .env file
        run: cp compose/.env.example compose/.env
      - name: Build the stack
        run: docker-compose -f compose/docker-compose.yml up -d
      # - name: Test # TODO add tests: portal, mapeo-bridge, minio, filebrowser, syncthing, terrastories
