name: server-push-test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate .env file
        run: cp compose/.env.example compose/.env
      - name: Build the stack
        run: docker-compose -f compose/docker-compose.yml up -d
      # - name: Test # TODO add tests
