name: Local docker-compose Stack Test
on:
  pull_request:
    paths:
      - 'docker/local/**'
    branches:
      - main
jobs:
  test-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate .env file
        run: cp docker/local/.env.example docker/local/.env
      - name: Build the stack
        run: docker-compose -f docker/local/docker-compose.yml up -d
      # - name: Test # TODO add tests: portal, mapeo-bridge, minio, filebrowser, syncthing, terrastories
