name: server-push-test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate .env file
        run: cp server/.env.example server/.env
      - name: Build the stack
        run: docker-compose up -f server/docker-compose.yml
      # - name: Test # TODO add tests
