name: Server docker-compose Stack
on:
  pull_request:
    branches:
      - main
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate .env file
        run: cp server/.env.example server/.env
      - name: Build the stack
        run: docker-compose -f server/docker-compose.yml up -d
      # - name: Test # TODO add tests: filebrowser, syncthing, mapeo-icons, fdroid-repo
